import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import AuthProvider from "@/context/AuthProvider"
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={process.env.THEME!}>
      <AuthProvider>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
        <div className="relative w-full flex item-center justify-center">
          <Navbar /> 
        </div>
        {children}
        <ToastContainer />
      </ThemeProvider>
      </body>

      </AuthProvider>
   </html>
  );
}
